spring:
  application:
    name: lgk-ai-code-service-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lgk_ai_code_service
    username: root
    password: 123456

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lgk.lgkaicodeservice.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
